name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

env:
  CI: true

jobs:
  test:
    name: "node v${{ matrix.node-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [10, 12, 14]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn install --prefer-offline

      - name: test
        run: yarn test
